async (page) => {
  const checks=[],errors=[],badResponses=[],requests=[];
  page.on('pageerror',err=>errors.push(err.message));
  page.on('response',res=>{if(res.status()>=400)badResponses.push([res.status(),res.url()]);});
  page.on('request',req=>requests.push(req.url()));
  const base=await page.evaluate(()=>new URL('./',location.href).href);
  const edition=base.includes(':8770')?'local':base.includes(':8768')?'static':'public';
  const assert=(ok,name)=>{if(!ok)throw new Error(name);checks.push(name);};
  async function graph(id){await page.waitForFunction(id=>!!document.getElementById(id)?._fullLayout,id,{timeout:30000});}
  async function view(id){await page.locator('#researchNav [data-view="'+id+'"]').click();await page.waitForFunction(id=>window.Workbench?.view===id,id);assert(await page.locator('.view-error').count()===0,'view '+id+' renders');}
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(base);await page.waitForFunction(()=>document.documentElement.dataset.researchReady==='true');await graph('priceChart');
  assert((await page.locator('.stat-grid').first().innerText()).includes('108.40%'),'overview original cohort ratio');
  assert(await page.locator('#directoryPanel').isHidden(),'directory is supporting, initially hidden');
  const initialApiRequests=requests.filter(u=>u.includes('/api/search'));
  assert(initialApiRequests.length===0,'overview does not load the full query catalog');
  await page.screenshot({path:'outputs/research_workbench/'+edition+'-overview.png',fullPage:true});
  await view('extremes');await graph('frontierChart');
  assert((await page.locator('#tailSummary').innerText()).includes('487,593'),'main n100 full group count');
  await page.selectOption('#tailN','1000');
  assert((await page.locator('#tailSummary').innerText()).includes('1,446'),'support selection updates exact group count');
  const plotCount=await page.evaluate(()=>document.getElementById('expressionChart').data.reduce((s,t)=>s+t.y.reduce((a,b)=>a+b,0),0));
  assert(plotCount===1749843543,'all-order histogram counts every supported expression');
  await page.selectOption('#expressionOrder','1');
  const oneCount=await page.evaluate(()=>document.getElementById('expressionChart').data.reduce((s,t)=>s+t.y.reduce((a,b)=>a+b,0),0));
  assert(oneCount===115,'one-field histogram count');
  await page.selectOption('#edgeOrder','19');
  assert(await page.locator('#edgeTable tbody tr').count()===57,'all high-order extreme ties remain listed');
  await page.selectOption('#biasBasis','original');
  assert((await page.locator('#biasText').innerText()).includes('105%'),'original calibration basis explained');
  await view('controls');await graph('comparisonChart');
  assert((await page.locator('#supportNote').innerText()).includes('117/325'),'joint controls expose original support retention');
  const gap=await page.evaluate(()=>document.getElementById('comparisonChart').data[0].y[2]);
  assert(Math.abs(gap-6.818059280670274)<1e-10,'focal standardized contrast is 6.818 pp');
  const focus=page.locator('#comparisonIntro [data-group-id="main-03600322"]');
  await focus.hover();await page.locator('#groupTooltip').waitFor({state:'visible'});
  assert((await page.locator('#groupTooltip').innerText()).includes('114.17%')&&(await page.locator('#groupTooltip').innerText()).includes('Burglary'),'ID hover includes mean and actual conditions');
  await page.keyboard.press('Escape');assert(await page.locator('#groupTooltip').isHidden(),'Escape dismisses hover');
  await focus.focus();await page.locator('#groupTooltip').waitFor({state:'visible'});
  assert((await page.locator('#groupTooltip').innerText()).includes('325'),'keyboard focus shows group explanation');
  await focus.press('Enter');await page.waitForFunction(()=>document.getElementById('detail').textContent.includes('main-03600322')&&!document.getElementById('detail').classList.contains('loading'));
  assert(await page.locator('#groupDialog').isVisible(),'group opens in an accessible detail dialog');
  assert((await page.locator('#detail').innerText()).includes('所有变量'),'full group distributions retained');
  assert((await page.url()).includes('view=controls'),'group detail preserves research view');
  await page.locator('#closeGroup').click();assert((await page.url()).includes('view=controls'),'closing detail preserves research view');
  const input=await page.evaluate(async()=>{const p=await (await fetch('research-data.json')).json();return p.controls.find(r=>r.cohort==='main'&&r.status!=='computed');});
  await page.selectOption('#candidateSelect',input.group_id);await page.selectOption('#removedSelect',input.removed_field);await page.selectOption('#controlScheme',input.scheme);
  assert((await page.locator('#supportNote').innerText()).includes('No common support'),'unavailable standardization is explicitly missing');
  const unavailable=await page.evaluate(()=>document.getElementById('comparisonChart').data[0].y[2]);assert(unavailable===null,'no common support is never plotted as zero');
  await page.selectOption('#candidateSelect','main-03600322');await page.selectOption('#controlScheme','joint');
  await page.locator('#comparisonChart').screenshot({path:'outputs/research_workbench/'+edition+'-controls-chart.png'});
  await view('interactions');await graph('interactionChart');
  const counts=await page.locator('.cell-card .cell-label').allTextContents();
  assert(counts.join(' ').includes('41')&&counts.join(' ').includes('315'),'I1 four observed cell counts');
  const chartRaw=await page.evaluate(()=>document.getElementById('interactionChart').data.map(t=>t.y));
  assert(Math.abs((chartRaw[1][1]-chartRaw[2][1])-(-8.26215049011309))<1e-8,'observed minus additive endpoint equals four-cell contrast');
  await page.selectOption('#interactionMetric','adjusted');
  const adjusted=await page.evaluate(()=>document.getElementById('interactionChart').data.map(t=>t.y));
  assert(Math.abs((adjusted[1][1]-adjusted[2][1])-(-9.72821447813157))<1e-8,'adjusted residual contrast uses pp correctly');
  const [adjustedCSV]=await Promise.all([page.waitForEvent('download'),page.locator('[data-export="interactionChart"]').click()]);await adjustedCSV.saveAs('outputs/research_workbench/'+edition+'-adjusted-four-cell.csv');
  await page.locator('#selectedInteraction').screenshot({path:'outputs/research_workbench/'+edition+'-interaction.png'});
  await page.selectOption('#interactionN','200');assert((await page.locator('#interactionCount').innerText()).includes('当前筛选'),'interaction support filter runs');
  await view('algebra');await graph('kernelChart');
  const diagonal=await page.evaluate(()=>document.getElementById('kernelChart').data[0].z.map((r,i)=>r[i]));assert(diagonal.every(x=>Math.abs(x-1)<1e-12),'normalized actual profile-kernel diagonal is one');
  await page.locator('#algebraDegree').fill('0');await page.locator('#algebraDegree').dispatchEvent('input');
  const constant=await page.evaluate(()=>document.getElementById('kernelChart').data[0].z.flat());assert(constant.every(x=>x===1),'degree zero kernel is constant');
  await page.locator('#algebraDegree').fill('2');await page.locator('#algebraDegree').dispatchEvent('input');await page.selectOption('#algebraN','1000');
  assert((await page.locator('#algebraSummary').innerText()).includes('0.186'),'saved n1000 order-two maximum error');
  await page.check('#weightedKernel');
  const weighted=await page.evaluate(()=>{const d=document.getElementById('kernelChart').data[0];return d.z.every((r,i)=>Math.abs(r[i]-d.customdata[i][i][3])<1e-10);});assert(weighted,'weighted kernel diagonal equals profile count');
  await page.locator('#nextProfiles').click();assert(await page.inputValue('#profileStart')==='24','matrix window moves to new real profiles');
  const [matrixDownload]=await Promise.all([page.waitForEvent('download'),page.locator('[data-export="kernelChart"]').click()]);await matrixDownload.saveAs('outputs/research_workbench/'+edition+'-kernel.csv');assert(matrixDownload.suggestedFilename().endsWith('.csv'),'matrix exports CSV');
  await page.locator('#kernelChart').screenshot({path:'outputs/research_workbench/'+edition+'-kernel.png'});
  await view('validation');await graph('performanceChart');assert((await page.locator('#validationSummary').innerText()).includes('3.44%'),'main spatial predictive gain');
  await page.selectOption('#validationScheme','forward');assert((await page.locator('#validationSummary').innerText()).includes('1,764'),'forward split shows actual evaluation support');
  await view('coverage');await graph('coverageChart');await page.selectOption('#coverageField','gate_known');assert((await page.locator('#coverageDefinition').innerText()).includes('0 / 8,595'),'unknown gated community data stays unavailable');
  await page.selectOption('#coverageMode','missing');const missing=await page.evaluate(()=>{const d=document.getElementById('coverageChart').data[0],i=d.customdata.findIndex(r=>r[0][0]==='gate_known');return d.z[i];});assert(missing.every(v=>v===100),'missingness toggle recomputes exact complement');
  await page.locator('#coverageChart').screenshot({path:'outputs/research_workbench/'+edition+'-coverage.png'});
  await page.selectOption('#researchCohort','positive_garage');await view('overview');assert((await page.locator('.stat-grid').first().innerText()).includes('2,048,170'),'garage cohort changes research counts');
  await view('extremes');await graph('expressionChart');assert((await page.locator('#expressionSummary').innerText()).includes('1,671,325,525'),'garage expression histogram uses its own census');
  await view('controls');assert((await page.locator('#supportNote').innerText()).includes('66/328'),'garage control support');
  await view('interactions');await graph('interactionChart');assert(await page.locator('.cell-card').count()===4,'garage four-cell explorer');
  await view('algebra');await graph('rankChart');assert((await page.locator('.stat-grid').first().innerText()).includes('1,449'),'garage observed-state algebra');
  await view('validation');assert((await page.locator('#validationSummary').innerText()).includes('-1.39%'),'garage validation retains negative result');
  await page.selectOption('#researchCohort','main');await view('directory');await page.waitForFunction(()=>document.querySelectorAll('#results tbody .group-row').length===50,{timeout:60000});
  assert((await page.locator('#filteredGroups').innerText())==='487,593','full directory retains exact n100 queries');
  await page.selectOption('#plotMode','tsne');await page.waitForFunction(()=>document.getElementById('scatter').data?.[0].x.length===1320);
  assert((await page.locator('#plotScope').innerText()).includes('不代表总体'),'projection scope remains explicit');
  await page.selectOption('#cohort','positive_garage');assert(await page.inputValue('#researchCohort')==='positive_garage','directory cohort stays synchronized with research cohort');
  await page.fill('#groupInput','M025');await page.locator('#lookupForm button[type=submit]').click();await page.waitForFunction(()=>document.getElementById('detail').textContent.includes('main-03600322')&&!document.getElementById('detail').classList.contains('loading'));
  await page.locator('#closeGroup').click();
  await page.setViewportSize({width:1200,height:900});await view('overview');await graph('priceChart');
  const compactOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert(!compactOverflow,'1200px desktop overview has no horizontal page overflow');
  await page.screenshot({path:'outputs/research_workbench/'+edition+'-desktop-compact.png',fullPage:true});
  await view('interactions');await graph('interactionChart');assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),'1200px desktop interaction view has no page overflow');
  await page.locator('#selectedInteraction').screenshot({path:'outputs/research_workbench/'+edition+'-desktop-compact-interaction.png'});
  await page.setViewportSize({width:1440,height:1000});await page.goto(base+'#view=controls&cohort=main&group=main-03600322');await page.waitForFunction(()=>document.documentElement.dataset.researchReady==='true'&&document.getElementById('groupDialog').open&&!document.getElementById('detail').classList.contains('loading'));
  assert((await page.locator('#detail').innerText()).includes('114.17%'),'existing deep link restores exact group');assert(await page.evaluate(()=>window.Workbench.view)==='controls','deep link restores research view');await page.locator('#closeGroup').click();
  assert(errors.length===0,'no uncaught JavaScript errors');assert(badResponses.length===0,'no failed asset/API responses');
  if(edition!=='local')assert(!requests.some(u=>/\/api\//.test(u)||u.includes(':8770')),'browser edition makes no local/backend query requests');
  return {status:'passed',edition,base,checks,errors,badResponses,requestCount:requests.length};
}
